name: reusable deploy
on: 
  workflow_call:
    inputs:
      artifact-name:
        description: The name of the downloaded artifact
        required : false
        default : dist
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: deploy
        run: echo "Deploying and uploading ..."
